version: 1.0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  verbosity: minimal
artifacts:
- path: '\src\TabContextSwitch\bin\Release\TabContextSwitch.vsix'
  name: build